#!/bin/bash
# ============================================================================
#  Mirza Bot - container entrypoint
#  - Generates config.php from environment variables
#  - Waits for the database to be ready
#  - Generates the cron schedule (cron job list)
#  - Starts Apache + cron via supervisord
#  - Initializes DB tables + Telegram webhook in the background once ready
# ============================================================================
set -e

APP_DIR="/var/www/html"
CONFIG_FILE="$APP_DIR/config.php"

log() { echo -e "\033[1;36m[mirza]\033[0m $*"; }
err() { echo -e "\033[1;31m[mirza]\033[0m $*" >&2; }

# ---------------------------------------------------------------------------
# 1) Validate the 4 user-supplied variables
# ---------------------------------------------------------------------------
: "${BOT_TOKEN:?BOT_TOKEN is required (Telegram bot token)}"
: "${ADMIN_CHAT_ID:?ADMIN_CHAT_ID is required (admin Telegram numeric ID)}"
: "${BOT_DOMAIN:?BOT_DOMAIN is required (e.g. bot.example.com - no https://)}"
: "${BOT_USERNAME:?BOT_USERNAME is required (bot username without @)}"

# Normalize: strip protocol & trailing slash from domain, leading @ from username
BOT_DOMAIN="${BOT_DOMAIN#http://}"
BOT_DOMAIN="${BOT_DOMAIN#https://}"
BOT_DOMAIN="${BOT_DOMAIN%/}"
BOT_USERNAME="${BOT_USERNAME#@}"

# ---------------------------------------------------------------------------
# 2) Database settings (auto, with sensible defaults matching docker-compose)
# ---------------------------------------------------------------------------
DB_HOST="${DB_HOST:-mariadb}"
DB_NAME="${DB_NAME:-mirzabot}"
DB_USER="${DB_USER:-mirzabot}"
DB_PASSWORD="${DB_PASSWORD:-mirzabot}"
DB_PORT="${DB_PORT:-3306}"

# ---------------------------------------------------------------------------
# 3) Generate config.php (always regenerated so env changes take effect)
# ---------------------------------------------------------------------------
log "Generating config.php ..."
cat > "$CONFIG_FILE" <<EOF
<?php
// Auto-generated by docker/entrypoint.sh - do NOT edit manually.
// Change values via Coolify environment variables instead.
\$request_exec_timeout = null;
\$dbhost = '${DB_HOST}';
\$dbname = '${DB_NAME}';
\$usernamedb = '${DB_USER}';
\$passworddb = '${DB_PASSWORD}';
\$connect = mysqli_connect(\$dbhost, \$usernamedb, \$passworddb, \$dbname);
if (\$connect->connect_error) { die("error" . \$connect->connect_error); }
mysqli_set_charset(\$connect, "utf8mb4");
\$options = [ PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false, ];
\$dsn = "mysql:host=\$dbhost;port=${DB_PORT};dbname=\$dbname;charset=utf8mb4";
try { \$pdo = new PDO(\$dsn, \$usernamedb, \$passworddb, \$options); } catch (\PDOException \$e) { error_log("Database connection failed: " . \$e->getMessage()); }
\$APIKEY = '${BOT_TOKEN}';
\$adminnumber = '${ADMIN_CHAT_ID}';
\$domainhosts = '${BOT_DOMAIN}';
\$usernamebot = '${BOT_USERNAME}';
?>
EOF
chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"

# ---------------------------------------------------------------------------
# 4) Wait for the database to be reachable
# ---------------------------------------------------------------------------
log "Waiting for database ${DB_HOST}:${DB_PORT} ..."
for i in $(seq 1 60); do
    if mysqladmin ping -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" --silent >/dev/null 2>&1; then
        log "Database is up."
        break
    fi
    if [ "$i" -eq 60 ]; then
        err "Database did not become ready in time. Continuing anyway (will retry on init)."
    fi
    sleep 2
done

# ---------------------------------------------------------------------------
# 5) Build the cron schedule (same jobs the bot would register itself)
#    Cron hits the bot over its public HTTPS domain (handled by Coolify proxy).
# ---------------------------------------------------------------------------
log "Configuring cron jobs ..."
CRON_FILE="/etc/cron.d/mirzabot"
BASE="curl -ksS --max-time 120 https://${BOT_DOMAIN}/cronbot"
cat > "$CRON_FILE" <<EOF
# Mirza Bot cron jobs (auto-generated)
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

*/15 * * * * root ${BASE}/statusday.php >/dev/null 2>&1
*/1  * * * * root ${BASE}/croncard.php >/dev/null 2>&1
*/1  * * * * root ${BASE}/NoticationsService.php >/dev/null 2>&1
*/5  * * * * root ${BASE}/payment_expire.php >/dev/null 2>&1
*/1  * * * * root ${BASE}/sendmessage.php >/dev/null 2>&1
*/3  * * * * root ${BASE}/plisio.php >/dev/null 2>&1
*/1  * * * * root ${BASE}/activeconfig.php >/dev/null 2>&1
*/1  * * * * root ${BASE}/disableconfig.php >/dev/null 2>&1
*/1  * * * * root ${BASE}/iranpay1.php >/dev/null 2>&1
0 */5 * * * root ${BASE}/backupbot.php >/dev/null 2>&1
*/2  * * * * root ${BASE}/gift.php >/dev/null 2>&1
*/30 * * * * root ${BASE}/expireagent.php >/dev/null 2>&1
*/15 * * * * root ${BASE}/on_hold.php >/dev/null 2>&1
*/2  * * * * root ${BASE}/configtest.php >/dev/null 2>&1
*/15 * * * * root ${BASE}/uptime_node.php >/dev/null 2>&1
*/15 * * * * root ${BASE}/uptime_panel.php >/dev/null 2>&1
*/1  * * * * root ${BASE}/lottery.php >/dev/null 2>&1
EOF
chmod 0644 "$CRON_FILE"
crontab "$CRON_FILE" 2>/dev/null || true

# ---------------------------------------------------------------------------
# 6) Background init: once Apache is up, create tables + set webhook
# ---------------------------------------------------------------------------
(
    # Wait for the local Apache to answer
    for i in $(seq 1 30); do
        if curl -ksS --max-time 5 "http://127.0.0.1/index.php" >/dev/null 2>&1; then
            break
        fi
        sleep 2
    done

    log "Initializing database tables (table.php) ..."
    # table.php creates all tables AND sets the Telegram webhook to the public domain
    curl -ksS --max-time 60 "http://127.0.0.1/table.php" >/dev/null 2>&1 || \
        err "table.php init returned an error (will be retried on next container start)."

    # Make sure the webhook points at the public HTTPS domain (table.php already does
    # this, but we re-assert it explicitly in case table.php failed midway).
    log "Setting Telegram webhook ..."
    curl -ksS --max-time 30 \
        -F "url=https://${BOT_DOMAIN}/index.php" \
        "https://api.telegram.org/bot${BOT_TOKEN}/setWebhook" >/dev/null 2>&1 || \
        err "Failed to set Telegram webhook."

    # Notify the admin that the bot is up
    curl -ksS --max-time 30 -X POST \
        "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
        -d chat_id="${ADMIN_CHAT_ID}" \
        -d text="✅ Mirza bot is deployed on Coolify and running. Send /start to begin." \
        >/dev/null 2>&1 || true

    log "Initialization finished."
) &

# ---------------------------------------------------------------------------
# 7) Hand off to supervisord (runs Apache + cron in the foreground)
# ---------------------------------------------------------------------------
log "Starting services (apache + cron) ..."
exec "$@"
